name: Deploy to S3

on:
  push:
    branches:
      - stage

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@v2

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: ap-south-1
        
    - name: pushing code to S3 Bucket
      run: |
        aws s3 sync . s3://ff-dev-metamorphosis --exclude '.git/*' --exclude '.github/*' --exclude 'deploy-live.sh' --exclude 'deploy-stage.sh' --exclude './idea' --exclude '.DS_Store' --exclude '.gitignore' --exclude 'README.md'
        echo "deploy done..."
        echo "Create Invalidation..."
        aws cloudfront create-invalidation --distribution-id E2YT97S0VT5NRM --paths "/*"
        echo "Invalidation Request Created..."
